name: List of tools and their sizes
on: workflow_dispatch
jobs:
  show_tools:
   runs-on: macos-14
   steps: 
    - name: disk usage 
      run: df -h
    - name: Node.js versions and their sizes 
      run: |
        echo "Node.js Versions and sizes"  
        du -sh /Users/runner/hostedtoolcache/node/* | sort -hr
    - name: Homebrew pacakges and sizes
      run: |
        echo "Homebrew packages and sizes"
        brew list --formula -1 | while read -r pkg; do
        du -sh "${HOMEBREW_CELLER}/$pkg" | awk '{print $1, $2}'
        done | sort -hr 
    - name: Xcode and sizes
      run: |
       du -sh /Applications/Xcode*.app 
    - name: Python version and sizes
      run: |
        du -sh /Users/runner/hostedtoolcache/Python/*2>/dev/null | sort -hr  







  